### ISSUE TITLE
为什么我把style粘进去没什么效果呢

### ISSUE THREAD

**Issue by asasdasasd** [kylin-z/vue-calendar#1]
custom example里面放到我的component之后没效果

**Comment by asasdasasd** [comment]
`<kl-calendar></kl-calendar>`这样写
` <kl-calendar/>`这样写有什么区别么
上边的style样式没效果，下边的有效果

**Comment by kylin-z** [comment]
是一样的

**Comment by asasdasasd** [comment]
@kylin-z  但是真的没效果诶
