### ISSUE TITLE
怎么传日期进去呢

### ISSUE THREAD

**Issue by asasdasasd** [kylin-z/vue-calendar#4]
不自动选择当前日期，自己传日期进去显示传入日期的月份

**Comment by asasdasasd** [comment]
好像是`new Date()`直接生成的，能不能抛出来个接口，让外边传进来啊

**Comment by asasdasasd** [comment]
每个格子的颜色能自己设置么

**Comment by kylin-z** [comment]
1.v1.3.1已添属性`default-date`用来指定初始渲染日期,具体请参考文档和demo
2.格子内部可以自定义 具体参考 [自定义渲染案例](http://kylin.himmas.cc/vue-calendar/example/demo.html)
